#!/bin/zsh

help_page()
{
	echo "Usage: video_arrange [-i] 'import directory' [-o] 'output directory'"
}

error()
{
	echo "$(tput setaf 202)Error: ${$(tput sgr0)}"$1
	help_page
	exit
}

move_files()
{
	miss=1
	for file in $1/*
	do
		if [[ $file == *$3* ]]
		then
			dir=$file
			if [[ $file == *.mkv  || $file == *.mp4 ]]
			then
				miss=0
				echo "${$(tput setaf 11)}Moving ${$(tput sgr0)}"$file"${$(tput setaf 11)} to ${$(tput sgr0)}"$2
				mv $file $2
			elif [[ -d $dir ]]
			then
				echo "${$(tput setaf 11)}Checking ${$(tput sgr0)}"$dir
				move_files $dir $2 $3
				if [[ $miss == 1 ]]
				then
					echo "$(tput setaf 202)No video files found in ${$(tput sgr0)}"\
$(echo $dir | rev | cut -d'/' -f2- | rev)
				else
					echo "${$(tput setaf 11)}Removing empty directory: ${$(tput sgr0)}"\
$(echo $dir | rev | cut -d'/' -f2- | rev)
					rm -rf $(echo $dir | rev | cut -d'/' -f2- | rev)
					miss=1
				fi
			fi
			
		fi
	done
}

setopt nullglob

if [[ $1 == "" ]]
then
	error "$(tput setaf 202)Missing arguments${$(tput sgr0)}"
fi

filter=""

while [ "$1" != "" ]; do
	case $1 in
		-i )		shift
				if [[ $1 != . ]]
				then
					var_in_dir=$1
				else
					var_in_dir=$(pwd)
				fi
				;;
		-o )		shift
				if [[ $1 != . ]]
				then
					var_out_dir=$1
				else
					var_out_dir=$(pwd)
				fi
				;;
		-f | --filter )	shift
				filter=$1
				;;		
		-h | --help )	help_page
				exit
       				;;
		* )		error "Invalid argument"
	esac		
	shift
done

echo "Input directory: "$var_in_dir 
echo "Output directory: "$var_out_dir 
echo "Filter: "$filter
echo ""

move_files $var_in_dir $var_out_dir $filter
